// Kiểm thử giao diện bằng Playwright: node test/giao-dien.js [thư-mục-ảnh]
const { chromium } = require(process.env.PW || "playwright");
const path = require("path");
const out = process.argv[2] || "/tmp";
(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 1360, height: 900 } });
  const page = await ctx.newPage();
  const loi = [];
  page.on("pageerror", (e) => loi.push("pageerror: " + e.message));
  page.on("console", (m) => { if (m.type() === "error") loi.push("console: " + m.text()); });
  page.on("dialog", (d) => d.accept());
  const url = "file://" + path.resolve(__dirname, "..", "index.html");
  const shot = (n) => page.screenshot({ path: path.join(out, n + ".png"), fullPage: false });
  await page.goto(url); await page.waitForTimeout(400); await shot("01-hom-nay");
  await page.goto(url + "#/muc-luc"); await page.waitForTimeout(300); await shot("02-muc-luc");
  const soDong = await page.$$eval(".lesson-row", (r) => r.length); console.log("dòng mục lục:", soDong);
  await page.goto(url + "#/bai/YC-01"); await page.waitForTimeout(300); await shot("03-chu-trinh");
  await page.goto(url + "#/bai/YC-01/doc"); await page.waitForTimeout(300);
  await page.fill('textarea[data-i="0"]', "Vì tắc đường thở giết nhanh hơn"); await shot("04-truoc-doc");
  await page.click("#bat-dau"); await page.waitForTimeout(300);
  const blocks = await page.$$("#prose [data-b]"); console.log("khối đánh dấu được:", blocks.length);
  await page.hover("#prose [data-b='5']"); await page.click("#prose [data-b='5'] > .flag-btn");
  await page.evaluate(() => document.querySelector("#prose [data-b='5']").scrollIntoView());
  await page.waitForTimeout(200); await shot("05-doc");
  await page.evaluate(() => document.querySelector("blockquote.chot").scrollIntoView({ block: "center" })); await page.waitForTimeout(100); await shot("05b-chot-an");
  await page.goto(url + "#/bai/YC-01/handout"); await page.waitForTimeout(1200);
  const fr = page.frame({ url: /about:srcdoc/ }) || page.frames()[1];
  const k = await fr.$$(".k"); console.log("ô handout:", k.length);
  await k[0].click(); await k[1].click(); await k[1].click(); await page.waitForTimeout(300);
  console.log("đếm:", await page.textContent("#ho-dem")); await shot("06-handout");
  await page.click("#ho-luu"); await page.waitForTimeout(200); await shot("06b-hoi"); await page.click(".hop .btn.chinh"); await page.waitForTimeout(300);
  await page.goto(url + "#/bai/YC-01/kiem-tra"); await page.waitForTimeout(300);
  await page.click('.q-card[data-i="0"] .opt[data-c="A"]'); await page.click('.q-card[data-i="1"] .xem'); await page.waitForTimeout(100); await shot("07-kiem-tra");
  await page.goto(url + "#/bai/YC-01/the"); await page.waitForTimeout(300); await page.click("#tt-on"); await page.waitForTimeout(200);
  await page.keyboard.press("Space"); await page.waitForTimeout(150); await shot("08-the");
  await page.keyboard.press("3"); await page.waitForTimeout(150);
  await page.goto(url + "#/bai/YC-01/giang"); await page.waitForTimeout(400);
  await page.check('[data-tc="0"]'); await page.fill("#g-vap", "Phản xạ áp cảm"); await page.fill("#g-ch", "Tại sao lactat tăng?"); await shot("09-giang");
  await page.click("#g-mo"); await page.click("#vd-bai .vd-rut"); await page.waitForTimeout(200);
  await page.click("#g-luu"); await page.waitForTimeout(300);
  await page.goto(url + "#/bai/YC-01/nhat-ky"); await page.waitForTimeout(300); await shot("10-nhat-ky-bai");
  await page.goto(url + "#/"); await page.waitForTimeout(300); await shot("11-hom-nay-sau");
  await page.goto(url + "#/nhat-ky"); await page.waitForTimeout(300); await shot("12-nhat-ky");
  await page.goto(url + "#/on-the"); await page.waitForTimeout(300); await shot("13-on-the");
  await page.goto(url + "#/phuong-phap"); await page.waitForTimeout(300); await shot("14-phuong-phap");
  await page.goto(url + "#/du-lieu"); await page.waitForTimeout(300);
  await page.setInputFiles("#file", [path.resolve(__dirname, "..", "noi-dung/YC-01/YC-01_anki.apkg")]); await page.waitForTimeout(800);
  console.log("nhập:", await page.textContent("#kq-nhap")); await shot("15-du-lieu");
  await page.goto(url + "#/bai/YC-03"); await page.waitForTimeout(300); await shot("16-chua-co");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(url + "#/bai/YC-01/doc"); await page.waitForTimeout(300); await shot("17-mobile-doc");
  await page.goto(url + "#/"); await page.waitForTimeout(300); await shot("18-mobile-hom-nay");
  const tran = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth); console.log("tràn ngang mobile:", tran);
  const st = await page.evaluate(() => JSON.parse(localStorage.getItem("dcck-hoc-v1")).bai["YC-01"]);
  console.log("trạng thái YC-01:", JSON.stringify({ hoc: st.hoc, giang: st.giang, handout: st.handout, kiemTra: st.kiemTra.length, danhDau: st.danhDau.length }));
  console.log(loi.length ? "LỖI:\n" + loi.join("\n") : "Không có lỗi JS");
  await browser.close();
})();
